[package]
name = "sparse_matrix"
version = "0.0.1"
authors = ["Tristan Konolige <tristan@konolige.com>"]

[dependencies]
ndarray = { path = "/Users/tristan/Build/rust-ndarray" }
itertools = "0.5.4"
num-integer = "*"
num-traits = "*"
rand = "*"
bit-vec = "*"
